Specify `import type` when applicable
oakserver/oak pull request #244
Opened 2020-09-14 09:31 UTC by esquevin

This fixes TS1371 that raises in deno 1.4.0 with the --unstable flag

Addresses #243

2020-09-14 10:10 UTC, kitsonk requested changes
Thanks.  Please see below.  Also, `.github/workflows/oak-ci.yml` should be updated so that the CI runs with the `--unstable` flag so that it would break if there was a regression, as well as running without `--unstable` as we shouldn't have any other dependency on `--unstable`

2020-09-14 10:10 UTC, kitsonk commented on .vscode/settings.json
> +{
Please don't commit this to the repo.

If would be find adding a `.gitignore`, but I have this ignored globally personally.

2020-09-15 07:29 UTC, esquevin commented on .vscode/settings.json
> +{
My bad, did not intend to add this file.

2020-09-15 23:53 UTC, kitsonk approved these changes
Awesome, thank you very much for the contribution.

2020-09-15 23:54 UTC, merged